### PR TITLE
Drop escaping of flash messages

### PR DESCRIPTION
**Pull request by nextekcarl**
Part of https://github.com/qualtik/Spark/issues/927 if that it approved, we should merge this to master on this repo, update that branch to use master again, and then merge that to master.

### CODE REVIEW

**Review by benrue — COMMENTED** [review]
The works item says to replace URI escape with CGI escape, but it looks like we are just removing escaping entirely. Is this appropriate?

**Comment by nextekcarl** [comment]
Yes. It turns out CGI escape will turn spaces into +, so "Updated the collateral" becomes "Updated+the+collateral". However, it helped mt to find out we only actually use Growlyflash in a couple of messages (Updating the collateral and assumptions set are among the only ones). That mirrors the finding from about a year ago where updating many of the flash messages for styling wasn't working.

In short, these are messages we display from our app, so we have control over them and we wouldn't out something harmful in them, and if we did, this library wouldn't be the correct place to protect against that.

**Review by benrue — APPROVED** [review]
:shipit: 

Is there going to be another PR for integrating this into the Spark repo?

**Comment by nextekcarl** [comment]
I was thinking I'd update the current one for fixing the flash messages to reference the new commit this will make on master when I merge it.

**Pull request merged**
